name: Daily Signal Message

on:
  schedule:
    - cron: '0 7 * * *'   # täglich 07:00 UTC
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Send Signal message
        run: |
          curl "https://signal.callmebot.com/signal/send.php?phone=${{ secrets.d3073803-46f1-4c72-afa5-704320c9b9ef }}&apikey=${{ secrets.560589 }}&text=Guten+Morgen"
