name: Daily Signal Message

on:
  schedule:
    - cron: '*/1 * * * *'   # jede minute (alternative schreibweise)
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Send Signal message
        run: |
          DATE=$(date +"%d.%m.%Y")
          curl "https://signal.callmebot.com/signal/send.php?phone=${{ secrets.PHONE }}&apikey=${{ secrets.APIKEY }}&text=Guten+Morgen"
